### PR TITLE
feat: add structured logging to NewRelic

### PR DESCRIPTION
**Pull request by rahulramkumar**
A step towards completing #22

### CODE REVIEW

**Comment by rahulramkumar** [comment]
Some screenshots of the logs after switching to logrus from the gin default logger:
Before
image

After
image

**Comment by rahulramkumar** [comment]
Some nice-to-haves that aren't in this PR

- Rate-limiting and queuing so we don't drop logs when we breach NewRelics API limits (I highly doubt we'll hit the 5k RPS limit any time soon)
- Retries
- Probably more, this is a good starting point until we hit a place where this needs to be changed

**Comment by disposedtrolley** [comment]
The NewRelic shipper is such a good candidate to be extracted to a standalone package. I was surprised that I couldn't find an existing implementation.

**Comment by awpala** [comment]
Closing for obsolescence. Repo is deprecated/inactive as of July 2022.

**Pull request closed without merging**
